# Day 15

In [1]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.09177795, 0.18502196, 0.54739216],
        [0.50571138, 0.97554421, 0.08431076],
        [0.61490434, 0.87685067, 0.15465484]],

       [[0.54545728, 0.0135935 , 0.92589073],
        [0.34995384, 0.26552802, 0.37640998],
        [0.13856654, 0.14266578, 0.68995395]],

       [[0.75498202, 0.90289635, 0.82169718],
        [0.00768075, 0.69011824, 0.27594021],
        [0.20382875, 0.84191139, 0.62921556]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 1.73668381,  1.60626142, -0.22899025, -0.52657399, -0.51698139],
       [-0.84939661,  0.83890733,  0.02465221, -0.61438997,  0.77326447],
       [-0.38944567,  1.46719058, -1.37316121,  0.33385058, -1.2000673 ],
       [-1.15343805, -1.48886073,  0.11600167,  0.25577713, -0.92560414],
       [-1.19525134, -0.15961964,  0.83206086,  0.79050438,  1.84662586]])

# 5. How to find common values between two arrays

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([0, 4, 7, 8, 9])

# 6. How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-09-07 2020-09-08 2020-09-09


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.99833996 0.65742273 0.36296521]
 [0.45246444 0.69288746 0.69233605]
 [0.01326377 0.15740969 0.38336379]]


Array2:
[[0.47834574 0.73442071 0.4140191 ]
 [0.27689285 0.33147972 0.85603507]
 [0.23477359 0.00368825 0.89321439]]


Equality: False


# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.33062299, 0.26076017, 0.54384563, 0.17157321, 0.04690421,
       0.        , 0.3423278 , 0.34761572, 0.5006936 , 0.82308672])

# 9. How to print all the values of an array?

In [10]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10. Subtract the mean of each row of a matrix

In [11]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 0.10564963, -0.08447109, -0.02117854],
       [ 0.32283463, -0.21367837, -0.10915626],
       [ 0.41008673, -0.30258079, -0.10750594]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 3., 5., 2., 3.])

# 12. How to get the diagonal of a dot product?

In [13]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([12, 27,  6])

# 13. How to find the most frequent value in an array?

In [14]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[6 7 0 4 2 9 8 0 5 8 2 3 4 2 6 9 4 2 6 9]


2

# 14. How to get the n largest values of an array

In [15]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

6

# 15. How to create a record array from a regular array?

In [17]:
arr = np.array([("AI", 2.5, 9),
                 ("ML", 7, 6),
             ("DL", 6.5, 1)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['AI' '2.5' '9']
 ['ML' '7' '6']
 ['DL' '6.5' '1']]

RECORD ARRAY


rec.array([(b'AI', 2.5, 9), (b'ML', 7. , 6), (b'DL', 6.5, 1)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])